/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini.ui;

import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import mini.util.XAuth;
import mini.util.XDialog;
import mini.util.XIcon;

/**
 *
 * @author LENOVO
 */
public class ManHinhChinhJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TrangChuJFrame
     */
    public ManHinhChinhJFrame() {
        initComponents();
        init();
        List<DanhMucBean> listDanhMuc = new ArrayList<>();
        listDanhMuc.add(new DanhMucBean("BanHang", jpnBanHang, jlbBanHang));
        listDanhMuc.add(new DanhMucBean("LichSu", jpnLichSu, jlbLichSu));
        listDanhMuc.add(new DanhMucBean("QLKhachHang", jpnQLKhachHang, jlbQLKhachHang));
        listDanhMuc.add(new DanhMucBean("QLNhanVien", jpnQLNhanVien, jlbQLNhanVien));
        listDanhMuc.add(new DanhMucBean("QLLSP", jpnQLLSP, jlbQLLSP));
        listDanhMuc.add(new DanhMucBean("QLSP", jpnQLSP, jlbQLSP));
        listDanhMuc.add(new DanhMucBean("DoanhThu", jpnDoanhThu, jlbDoanhThu));
        listDanhMuc.add(new DanhMucBean("QLHoaDon", jpnQLHoaDon, jlbQLHoaDon));
        listDanhMuc.add(new DanhMucBean("Pass", jpnPass, jlbPass));
        listDanhMuc.add(new DanhMucBean("ChangeUser", jpnChangeUser, jlbChangeUser));
        
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView (jpnChangeUser, jlbChangeUser);
        controller.setEvent(listDanhMuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnBanHang = new javax.swing.JPanel();
        jlbBanHang = new javax.swing.JLabel();
        jpnLichSu = new javax.swing.JPanel();
        jlbLichSu = new javax.swing.JLabel();
        jpnPass = new javax.swing.JPanel();
        jlbPass = new javax.swing.JLabel();
        jpnManager = new javax.swing.JPanel();
        jpnQLNhanVien = new javax.swing.JPanel();
        jlbQLNhanVien = new javax.swing.JLabel();
        jpnQLLSP = new javax.swing.JPanel();
        jlbQLLSP = new javax.swing.JLabel();
        jpnQLSP = new javax.swing.JPanel();
        jlbQLSP = new javax.swing.JLabel();
        jpnDoanhThu = new javax.swing.JPanel();
        jlbDoanhThu = new javax.swing.JLabel();
        jpnQLHoaDon = new javax.swing.JPanel();
        jlbQLHoaDon = new javax.swing.JLabel();
        jpnQLKhachHang = new javax.swing.JPanel();
        jlbQLKhachHang = new javax.swing.JLabel();
        jpnChangeUser = new javax.swing.JPanel();
        jlbChangeUser = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini Mart\n");
        setBackground(new java.awt.Color(255, 255, 255));

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/giohang.png"))); // NOI18N
        jLabel1.setText("MINI MART\n");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jpnBanHang.setBackground(new java.awt.Color(153, 153, 255));

        jlbBanHang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbBanHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbBanHang.setText("Bán hàng");

        javax.swing.GroupLayout jpnBanHangLayout = new javax.swing.GroupLayout(jpnBanHang);
        jpnBanHang.setLayout(jpnBanHangLayout);
        jpnBanHangLayout.setHorizontalGroup(
            jpnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBanHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbBanHang)
                .addGap(116, 116, 116))
        );
        jpnBanHangLayout.setVerticalGroup(
            jpnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBanHangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlbBanHang)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpnLichSu.setBackground(new java.awt.Color(153, 153, 255));

        jlbLichSu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbLichSu.setForeground(new java.awt.Color(255, 255, 255));
        jlbLichSu.setText("Lịch sử");

        javax.swing.GroupLayout jpnLichSuLayout = new javax.swing.GroupLayout(jpnLichSu);
        jpnLichSu.setLayout(jpnLichSuLayout);
        jpnLichSuLayout.setHorizontalGroup(
            jpnLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLichSuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbLichSu)
                .addGap(131, 131, 131))
        );
        jpnLichSuLayout.setVerticalGroup(
            jpnLichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLichSuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbLichSu)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpnPass.setBackground(new java.awt.Color(153, 153, 255));

        jlbPass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbPass.setForeground(new java.awt.Color(255, 255, 255));
        jlbPass.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jpnPassLayout = new javax.swing.GroupLayout(jpnPass);
        jpnPass.setLayout(jpnPassLayout);
        jpnPassLayout.setHorizontalGroup(
            jpnPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnPassLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbPass)
                .addGap(95, 95, 95))
        );
        jpnPassLayout.setVerticalGroup(
            jpnPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPassLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbPass)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpnManager.setBackground(new java.awt.Color(102, 102, 102));

        jpnQLNhanVien.setBackground(new java.awt.Color(153, 153, 255));

        jlbQLNhanVien.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLNhanVien.setText("Quản lý nhân viên");

        javax.swing.GroupLayout jpnQLNhanVienLayout = new javax.swing.GroupLayout(jpnQLNhanVien);
        jpnQLNhanVien.setLayout(jpnQLNhanVienLayout);
        jpnQLNhanVienLayout.setHorizontalGroup(
            jpnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLNhanVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQLNhanVien)
                .addGap(58, 58, 58))
        );
        jpnQLNhanVienLayout.setVerticalGroup(
            jpnQLNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLNhanVienLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbQLNhanVien)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpnQLLSP.setBackground(new java.awt.Color(153, 153, 255));

        jlbQLLSP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbQLLSP.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLLSP.setText("Quản lý loại sản phẩm");

        javax.swing.GroupLayout jpnQLLSPLayout = new javax.swing.GroupLayout(jpnQLLSP);
        jpnQLLSP.setLayout(jpnQLLSPLayout);
        jpnQLLSPLayout.setHorizontalGroup(
            jpnQLLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLLSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQLLSP)
                .addGap(36, 36, 36))
        );
        jpnQLLSPLayout.setVerticalGroup(
            jpnQLLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLLSPLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbQLLSP)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpnQLSP.setBackground(new java.awt.Color(153, 153, 255));

        jlbQLSP.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbQLSP.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLSP.setText("Quản lý sản phẩm");

        javax.swing.GroupLayout jpnQLSPLayout = new javax.swing.GroupLayout(jpnQLSP);
        jpnQLSP.setLayout(jpnQLSPLayout);
        jpnQLSPLayout.setHorizontalGroup(
            jpnQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLSPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQLSP)
                .addGap(61, 61, 61))
        );
        jpnQLSPLayout.setVerticalGroup(
            jpnQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLSPLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbQLSP)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpnDoanhThu.setBackground(new java.awt.Color(153, 153, 255));

        jlbDoanhThu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        jlbDoanhThu.setText("Doanh Thu");

        javax.swing.GroupLayout jpnDoanhThuLayout = new javax.swing.GroupLayout(jpnDoanhThu);
        jpnDoanhThu.setLayout(jpnDoanhThuLayout);
        jpnDoanhThuLayout.setHorizontalGroup(
            jpnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jlbDoanhThu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDoanhThuLayout.setVerticalGroup(
            jpnDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDoanhThuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbDoanhThu)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpnQLHoaDon.setBackground(new java.awt.Color(153, 153, 255));

        jlbQLHoaDon.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbQLHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLHoaDon.setText("Quản lý hóa đơn");

        javax.swing.GroupLayout jpnQLHoaDonLayout = new javax.swing.GroupLayout(jpnQLHoaDon);
        jpnQLHoaDon.setLayout(jpnQLHoaDonLayout);
        jpnQLHoaDonLayout.setHorizontalGroup(
            jpnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQLHoaDon)
                .addGap(76, 76, 76))
        );
        jpnQLHoaDonLayout.setVerticalGroup(
            jpnQLHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLHoaDonLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlbQLHoaDon)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnManagerLayout = new javax.swing.GroupLayout(jpnManager);
        jpnManager.setLayout(jpnManagerLayout);
        jpnManagerLayout.setHorizontalGroup(
            jpnManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnQLNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQLLSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQLSP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnQLHoaDon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnManagerLayout.setVerticalGroup(
            jpnManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnManagerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnQLNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnQLLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnQLHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQLKhachHang.setBackground(new java.awt.Color(153, 153, 255));

        jlbQLKhachHang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbQLKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        jlbQLKhachHang.setText("Quản lý khách hàng");

        javax.swing.GroupLayout jpnQLKhachHangLayout = new javax.swing.GroupLayout(jpnQLKhachHang);
        jpnQLKhachHang.setLayout(jpnQLKhachHangLayout);
        jpnQLKhachHangLayout.setHorizontalGroup(
            jpnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQLKhachHangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbQLKhachHang)
                .addGap(43, 43, 43))
        );
        jpnQLKhachHangLayout.setVerticalGroup(
            jpnQLKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQLKhachHangLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlbQLKhachHang)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jpnChangeUser.setBackground(new java.awt.Color(153, 153, 255));

        jlbChangeUser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlbChangeUser.setForeground(new java.awt.Color(255, 255, 255));
        jlbChangeUser.setText("Người dùng");

        javax.swing.GroupLayout jpnChangeUserLayout = new javax.swing.GroupLayout(jpnChangeUser);
        jpnChangeUser.setLayout(jpnChangeUserLayout);
        jpnChangeUserLayout.setHorizontalGroup(
            jpnChangeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChangeUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbChangeUser)
                .addGap(97, 97, 97))
        );
        jpnChangeUserLayout.setVerticalGroup(
            jpnChangeUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChangeUserLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbChangeUser)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnLichSu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnQLKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnChangeUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnLichSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnQLKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnChangeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("KẾT THÚC");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addGap(44, 44, 44))))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        if(XDialog.confirm("Bạn muốn kết thúc?")){
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManHinhChinhJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManHinhChinhJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbBanHang;
    private javax.swing.JLabel jlbChangeUser;
    private javax.swing.JLabel jlbDoanhThu;
    private javax.swing.JLabel jlbLichSu;
    private javax.swing.JLabel jlbPass;
    private javax.swing.JLabel jlbQLHoaDon;
    private javax.swing.JLabel jlbQLKhachHang;
    private javax.swing.JLabel jlbQLLSP;
    private javax.swing.JLabel jlbQLNhanVien;
    private javax.swing.JLabel jlbQLSP;
    private javax.swing.JPanel jpnBanHang;
    private javax.swing.JPanel jpnChangeUser;
    private javax.swing.JPanel jpnDoanhThu;
    private javax.swing.JPanel jpnLichSu;
    private javax.swing.JPanel jpnManager;
    private javax.swing.JPanel jpnPass;
    private javax.swing.JPanel jpnQLHoaDon;
    private javax.swing.JPanel jpnQLKhachHang;
    private javax.swing.JPanel jpnQLLSP;
    private javax.swing.JPanel jpnQLNhanVien;
    private javax.swing.JPanel jpnQLSP;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
    public void showJDialog(JDialog dialog){
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    public void init() {
        this.setIconImage(XIcon.getIcon("/image/icon - Copy.png").getImage());
        this.setLocationRelativeTo(null);
        showJDialog(new ManHinhChoJDialog(this, true));
        showJDialog(new DangNhapJDialog(this, true));
        updateUIAfterLogin();
    }
    public void updateUIAfterLogin() {
        if (!XAuth.user.isManager()) {
            jPanel1.remove(jpnManager);
        } else {
            if (!Arrays.asList(jPanel1.getComponents()).contains(jpnManager)) {
                jPanel1.add(jpnManager); // Nếu bị remove rồi thì add lại
            }
        }
        jPanel1.revalidate();
        jPanel1.repaint();
    }
    public JPanel getJpnView() {
    return jpnView;
    }
    public void showBillJDialog() {
        ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
        controller.setView (jpnBanHang, jlbBanHang);
    }
}
